django-web/messenger/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'messenger'

urlpatterns = [
    url(r"^$", views.messenger, name="messengerhome"),
    url(r"^(?P<user_id>[0-9]+)/$", views.messenger_session),
    url(r"^compose$", views.compose, name="compose"),
]

django-web/slurmui/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.sitehome, name="siteindex"),
    url(r'^user/$', views.user_home, name='userhome'),
    url(r'^user/(?P<user_id>[0-9]+)', views.user_home),
    url(r'^account/', include('accounts.urls')),
    url(r'^info/', include('infopage.urls')),
    url(r'^settings/$', views.settingspage, name="settingspage"),
    url(r'^settings/addserver/', views.serversettings_addserver, name="settings_addserver"),
    url(r'^cmd/', include('webcmd.urls')),
    url(r'^support/', include('support.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login_view, name='login'),
    url(r'^messenger/', include('messenger.urls')),
]

django-web/webcmd/urls.py
from django.conf.urls import url

from . import views

app_name = 'webcmd'
urlpatterns = [
    url(r'^$', views.cmd_selection, name='index'),
    url(r'^cmd/$', views.cmd, name='cmd'),
    url(r'^cmd/(?P<server_name>.+)/$', views.cmd, name='server_cmd'),
    url(r'^clear', views.clear_cmd, name='clear_cmd')
]

django-web/templates/login.html
{% extends 'navigation.html' %}

{% load static %}

{% block styles %}
<!--<link rel="stylesheet" type="text/css" href="{% static 'mainpage.css' %}" />-->
{% endblock %}

{% block title %}
<title>SLURM Companion - Login</title>
{% endblock %}

{% block content %}
    <div class="content">
    {% if form %}
        <div id="login-form">
            Login:
            <form action={% url 'login' %} method="post">
                {% csrf_token %}

                <table>
                    {{ form.as_table }}
                </table>
                <button class="button" type="submit" value="Login"/>
            </form>
        </div>
    {% elif not login_failed %}
        <div class="login-msg">Logged in as <span class="username">{{ username }}</span>.</div>
        <form>
            <button class="button" type="submit" value="Logout" action="&logout" style="background: none" />
        </form>
    {% endif %}

    {% if login_failed %}
        <div class="warning">Login failed!</div>
    {% endif %}
    </div>
{% endblock %}

django-web/templates/navigation.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/companion.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/navigation.css' %}" />
    {% block styles %}
    {% endblock %}
    {% block scripts %}
    {% endblock %}
    {% block title %}
    {% endblock %}
</head>

<body>
<header class="page-header">
    <div class="banner">SLURM Companion Utilities</div>

    {% if not login_disabled %}
        <div class="login-mask">
        {% if not logged_in %}
            <div class="login-form">
                Login:
                <form action={% url 'login' %} method="post">
                    {% csrf_token %}

                    {{ login_form }}
                    <button class="button" type="submit" value="Login">Login</button>
                </form>
            </div>
        {% elif logged_in and not login_failed %}
            <div class="login-msg">Logged in as <span class="username">{{ username }}</span>.</div>
            <form action="" method="get">
                <input type="hidden" name="logout" />
                <button class="button" type="submit" value="Logout">Logout</button>
            </form>
        {% endif %}

        {% if login_failed %}
            <div class="dropout warning">Login failed!</div>
        {% endif %}
        </div>
    {% endif %}
</header>

<nav class="nav">
    <ul>
        <li>
            <a href={% url 'infopageindex' %}>Info</a>
        </li>
        <li>
            <a href="">About</a>
        </li>
        {% if logged_in %}
        <li>
            <a href={% url 'userhome' %}>My Account</a>
        </li>
        <li>
            <a href={% url 'settingspage' %}>Settings</a>
        </li>
        <li>
            <a href={% url 'webcmd:index' %}>Command Prompt</a>
        </li>
        <li>
            <a>File Manager</a>
        </li>
        <li>
            <a>SLURM UI</a>
        </li>
        <li>
            <a>SLURM Statistics</a>
        </li>
        <li>
            <a href={% url 'messenger:messengerhome' %}>Messenger</a>
        </li>
        <li>
            <a href={% url 'supportindex' %}>Support</a>
        </li>
        {% endif %}
    </ul>
</nav>

<div class="content">
    {% block content %}
    {% endblock %}
</div>

<footer class="page-footer">
    <div class="footer-text">
        Copyright 2016-2017 Thomas Mertz
    </div>
</footer>
</body>
</html>

django-web/templates/server_settings_red.html
{% extends 'navigation.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'settings.css' %}" />
{% endblock %}


{% block content %}
    {% if error_message %}
        <div class="warning">{{ error_message }}</div>
    {% elif test_status %}
        <div class="notification">{{ test_msg }} <br /> Saved connection data: {{ profile }} for {{ server_name }} at {{ url }}.</div>
    {% else %}
        <div class="warning">Connection test failed! {{ test_msg }}</div>
    {% endif %}
    

    <a href={% url 'settingspage' %}>Add another server</a>
{% endblock %}

django-web/templates/settings.html
{% extends 'navigation.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'settings.css' %}" />
{% endblock %}


{% block content %}
    {% if error_message %}
        <div class="warning">{{ error_message }}</div>
    {% endif %}

    <form action="{% url 'settings_addserver' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Add a server</legend>
            <table>
                {% for field in add_server_form %}
                    <tr><th>{{ field.label_tag }}</th>
                    <td>{{ field }}</td>
                    {% if field.help_text %}
                        <td>{{ field.help_text }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                {% endfor %}
                    </tr>
            </table>
            <input type="submit" value="Add Server" />
        </fieldset>
    </form>
{% endblock %}

django-web/templates/sitehome.html
{% extends 'navigation.html' %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'mainpage.css' %}" />

{% block content %}
    Start page
    <!--
    <div class="content">
    {% if form %}
        <div id="login-form">
            Login:
            <form action={% url 'siteindex' %} method="post">
                {% csrf_token %}

                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Login"/>
            </form>
        </div>
    {% elif not login_failed %}
        <div class="login-msg">Logged in as <span class="username">{{ username }}</span>.</div>
        <form>
            <input type="submit" value="Logout" action="&logout" style="background: none" />
        </form>
    {% endif %}

    {% if login_failed %}
        <div class="warning">Login failed!</div>
    {% endif %}
    </div>
    -->
{% endblock %}

django-web/templates/userhome.html
{% extends 'navigation.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/userhome.css' %}" />
{% endblock %}

{% block content %}
<div class='content-container'>
    <div class='box user-option'>
        News
    </div>
    <div class='box user-option'>
        Shell
    </div>
    <div class='box user-option'>
        Options
    </div>
    <div class='box user-option'>
        Support
    </div>
    <div class='box user-option'>
        Messages
    </div>
</div>
<div class='content-container'>
    <h4>Account Overview</h4>
    
</div>
{% endblock %}