django-web/slurmui/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.sitehome, name="siteindex"),
    url(r'^user/$', views.user_home, name='userhome'),
    url(r'^user/(?P<user_id>[0-9]+)', views.user_home),
    url(r'^account/', include('accounts.urls')),
    url(r'^info/', include('infopage.urls')),
    url(r'^settings/$', views.settingspage, name="settingspage"),
    url(r'^settings/addserver/', views.serversettings_addserver, name="settings_addserver"),
    url(r'^cmd/', include('webcmd.urls')),
    url(r'^support/', include('support.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login_view, name='login'),
    url(r'^messenger/', include('messenger.urls')),
]

django-web/webcmd/urls.py
from django.conf.urls import url

from . import views

app_name = 'webcmd'
urlpatterns = [
    url(r'^$', views.cmd_selection, name='index'),
    url(r'^cmd/$', views.cmd, name='cmd'),
    url(r'^cmd/(?P<server_name>.+)/$', views.cmd, name='server_cmd'),
    url(r'^clear', views.clear_cmd, name='clear_cmd')
]

django-web/webcmd/models.py
from django.db import models

# Create your models here.

"""
class Command(models.Model):
    
    command_text = models.CharField()
    
    def text(self):
        return command_text

class Response(models.Model):
    command = models.ForeignKey(Command, on_delete=models.CASCADE)
    response_text = models.CharField()

    def text(self):
        return response_text
"""

class Command(models.Model):
    command_text = models.CharField(max_length=200)

    def __str__(self):
        return self.command_text

django-web/webcmd/forms.py
from django import forms

class CmdForm(forms.Form):
    input_cmd = forms.CharField(label='Enter Command', required=False)
    #output_field = forms.CharField(widget=forms.Textarea, required=False)

    """
    def __init__(self, string=None):
        forms.Form.__init__(self)
        if (string is not None):
            self.cleaned_data['input_command'] = string
    """

django-web/webcmd/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .forms import CmdForm
from .cmdtext import CmdText, Command, Response
from slurmui.views import get_default_context, perform_logout
from sshcomm.models import UserData
from sshcomm.security import decrypt_Crypto
from sshcomm.comm import ping

# Create your views here.

PROMPT_SYMBOL = "?>"

def index(request):
    return HttpResponse("index")
    


def clear_cmd(request):

    # determine login status to handle the login/logout forms
    context = get_default_context(request)

    login_disabled = not context['logged_in']
    context.update({'login_disabled': login_disabled, })
    
    try:
        del request.session['command_list']
        del request.session['response_list']
    except:
        pass
    

    form = CmdForm()
    context.update({'cmd_res_list': [[], []],
               'form': form
              })
    
    #return render(request, 'webcmd/cmd.html', context=context)
    return HttpResponseRedirect(reverse("cmd/cmd"))

@login_required
def cmd(request, server_name=None, context=None):
    
    if context is None:
        # determine login status to handle the login/logout forms
        context = {}

    if request.method == 'GET':
        request, context = perform_logout(request)

    context.update(get_default_context(request))

    login_disabled = not context['logged_in']
    context.update({'login_disabled': login_disabled, })
    if login_disabled:
        return HttpResponseRedirect(reverse("siteindex"))
    ##
    
    request.session.set_expiry(0)

    if request.method == 'GET':
        if 'clear-shell' in request.GET:
            try:
                del request.session['command_list']
                del request.session['response_list']
            except KeyError:
                pass
            request.session.flush()
            cmd_res_list = [[], []]
            context.update({'cmd_res_list': request.session['command_list']})#cmd_res_list}
        else:
            context.update({'cmd_res_list': [[], []]})
        
        form = CmdForm()

    elif request.method == 'POST':
        form = CmdForm(request.POST)

        if form.is_valid():
            
            cmd_string = form.cleaned_data['input_cmd']
            if 'command_list' not in request.session:
                request.session['command_list'] = []
            cur_cmd = Command("user@192.168.178.112:~$" + PROMPT_SYMBOL + cmd_string)
            request.session['command_list'].append(cur_cmd[:])
            cur_cind = len(request.session['command_list'])

            # retrieve server data
            try:
                profile = UserData.objects.get(user=request.user, profile=server_name)
            except:
                raise
            
            try:
                import sshcomm.comm as comm
                # This is just experimental and will be replaced
                cdata = comm.ConnectionData("192.168.178.112", "user", " ")
                '''
                cdata = comm.ConnectionData(profile.url, 
                                            decrypt_Crypto(username, request.session.hashkey), 
                                            decrypt_Crypto(password, request.session.hashkey)
                                            )
                '''
                response_string = comm.run_command(cdata, cmd_string)
            except Exception as e:
                response_string = "[backend failed: {}] response to ".format(e) + cmd_string
            if 'response_list' not in request.session:
                request.session['response_list'] = []
            cur_res = Response(response_string, cur_cind)
            request.session['response_list'].append(cur_res[:])
            cur_rind = len(request.session['response_list'])

            cmd_res_list = []
            for c,r in zip(request.session['command_list'], request.session['response_list']):
                cmd_res_list.append([c, r])

            # update response
            #request.session['command_list'][-1].response = cur_rind

            cmd_string = PROMPT_SYMBOL + cmd_string
            response_string = PROMPT_SYMBOL + response_string

            # TEST
            #out_string = ""
            #for c in request.session['command_list']:
            #    out_string += c + "\n"

            #form.cleaned_data['output_field'] = "response"
            context.update({'cmd': request.session['command_list'],
                       'response': response_string,
                       'command_list': request.session['command_list'],
                       'response_list': request.session['response_list'],
                       'cmd_res_list': cmd_res_list
                      })
            
        else:
            #context = {}
            pass
        #return HttpResponseRedirect('/cmd/cmd')
    
    else:
        form = CmdForm()
        #context = {}
    
    context.update({'form': form})
    

    #return HttpResponse("cmd")
    #return render(request, 'webcmd/cmd.html', context=context)
    return render(request, 'webcmd/cmd_ws.html', context=context)

def get_paragraph_string(string):
    out = "<p>"
    out += string
    out += "</p>"

    return out

def cmd_selection(request, context=None):
    """
    Offers all the user's profiles for selection.
    """
    # determine login status to handle the login/logout forms
    context = {}

    if request.method == 'GET':
        request, context = perform_logout(request)

    context.update(get_default_context(request))

    login_disabled = not context['logged_in']
    context.update({'login_disabled': login_disabled, })
    ##
    if login_disabled:
        return HttpResponseRedirect(reverse('siteindex'))

    server_list = UserData.objects.filter(owner=request.user)

    #context.update({'server_list': server_list})

    server_status = []
    for s in server_list:
        server_status.append([s, ping(s.server.server_url)])
    context.update({'server_list': server_status})

    return render(request, 'webcmd/cmd_select.html', context=context)

django-web/webcmd/templates/webcmd/cmd.html
{% extends "navigation.html" %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'webcmd/style.css' %}" />

{% block content %}
<form action="/cmd/cmd" method="post">
    {% csrf_token %}
    
    <!--
    <p class="command">{{ cmd }}</p>
    <p class="response">{{ response }}</p>
    <br />
    -->
    <h4>Active Shell</h4>
    <div class="commandline">
        {% for c in cmd_res_list %}
            {% for cl in c.0 %}
                <div class="command">{{ cl }}</div>
            {% endfor %}
            {% for rl in c.1 %}
                <div class="response">{{ rl }}</div>
            {% endfor %}
        {% endfor %}
    </div>
    {{ form }}
    <input type="submit" value="Submit" />
</form>


<form action="/cmd/clear" method="post">
    {% csrf_token %}
    <input type="submit" value="Clear history" />
</form>

{% endblock %}

django-web/webcmd/templates/webcmd/cmd_manage.html
{% extends 'navigation.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'webcmd/css/style.css' %}" />
{% endblock %}

{% block content %}

<h3>Select profile</h3>
<div class="autooverflow">
<table class="server_list">
    <tr><th class="select-all col-select"><input type="checkbox" />Select all</th><th>Profile Name</th><th>URL</th><th>Availability/Status</th><th></th><th></th></tr>
{% for server in server_list %}
        <tr class="profile_row">
            <td class="col-select"><input type="checkbox" /></td><td>{{server.0.profile}}</td><td>{{server.0.server.server_url}}</td>
        <td>
            {% if server.1 %}
            <span class="status-ok-icon"><img src="{% static 'webcmd/img/status-green-icon.png' %}" alt="{{server.1}}" /></span>
            {% else %}
            <span class="status-notok-icon"><img src="{% static 'webcmd/img/status-red-icon.png' %}" alt="{{server.1}}" /></span>
            {% endif %}
        </td>
        <td>Edit</td>
        <td><span class="delete-x"><img src="{% static 'webcmd/img/delete-x.png' %}" alt="Delete" /></span></td>
        </tr>
{% endfor %}
</table>
</div>

<form action="" method="GET">
    <select>
        <option value="delete">Delete</option>
    </select>
    <button type="submit">Go</button>
</form>
{% endblock %}

django-web/webcmd/templates/webcmd/cmd_select.html
{% extends 'navigation.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'webcmd/css/style.css' %}" />
{% endblock %}

{% block content %}

<h3>Select profile</h3>
<table class="server_list">
    <tr><th><input type="checkbox" />Select all</th><th>Profile Name</th><th>URL</th><th>Availability/Status</th><th></th></tr>
{% for server in server_list %}
        <tr class="profile_row">
            <td><input type="checkbox" /></td><td><a href="{% url 'webcmd:server_cmd' server_name=server.0.profile %}">{{server.0.profile}}</a></td><td>{{server.0.server.server_url}}</td>
        <td>
            {% if server.1 %}
            <span class="status-ok-icon"><img src="{% static 'webcmd/img/status-green-icon.png' %}" alt="{{server.1}}" /></span>
            {% else %}
            <span class="status-notok-icon"><img src="{% static 'webcmd/img/status-red-icon.png' %}" alt="{{server.1}}" /></span>
            {% endif %}
        </td>
        <td>Edit</td>
        </tr>
{% endfor %}
</table>

{% endblock %}

django-web/webcmd/templates/webcmd/cmd_ws.html
{% extends "navigation.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'webcmd/css/style.css' %}" />
{% endblock %}

{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'webcmd/js/cmdscript.js' %}"></script>
{% endblock %}


{% block content %}
<h4>Active Shell</h4>
<!--<form action="/cmd/cmd" method="post">
    {% csrf_token %}
    
    <div class="commandline">
        {% for c in cmd_res_list %}
            {% for cl in c.0 %}
                <div class="command">{{ cl }}</div>
            {% endfor %}
            {% for rl in c.1 %}
                <div class="response">{{ rl }}</div>
            {% endfor %}
        {% endfor %}
    </div>
    {{ form }}
    
</form>-->
<div id="cmdWindow">
        
</div>
<span id="cmdPrompt"></span>
<input type="text" id="command_input" />
<input type="button" id="submit_cmd" onclick="submit()" value="Submit" />


<form action="/cmd/clear" method="post">
    {% csrf_token %}
    <input type="submit" value="Clear history" />
</form>

{% endblock %}